export const COUNTRIES = [
  { code: '52', flag: '🇲🇽', name: 'México' },
  { code: '1', flag: '🇨🇦', name: 'Canadá' },
  { code: '1', flag: '🇺🇸', name: 'Estados Unidos' },
  { code: 'separator', flag: '', name: '---' },
  { code: '49', flag: '🇩🇪', name: 'Alemania' },
  { code: '54', flag: '🇦🇷', name: 'Argentina' },
  { code: '55', flag: '🇧🇷', name: 'Brasil' },
  { code: '56', flag: '🇨🇱', name: 'Chile' },
  { code: '57', flag: '🇨🇴', name: 'Colombia' },
  { code: '506', flag: '🇨🇷', name: 'Costa Rica' },
  { code: '593', flag: '🇪🇨', name: 'Ecuador' },
  { code: '503', flag: '🇸🇻', name: 'El Salvador' },
  { code: '34', flag: '🇪🇸', name: 'España' },
  { code: '33', flag: '🇫🇷', name: 'Francia' },
  { code: '502', flag: '🇬🇹', name: 'Guatemala' },
  { code: '504', flag: '🇭🇳', name: 'Honduras' },
  { code: '39', flag: '🇮🇹', name: 'Italia' },
  { code: '505', flag: '🇳🇮', name: 'Nicaragua' },
  { code: '507', flag: '🇵🇦', name: 'Panamá' },
  { code: '51', flag: '🇵🇪', name: 'Perú' },
  { code: '44', flag: '🇬🇧', name: 'Reino Unido' },
  { code: '598', flag: '🇺🇾', name: 'Uruguay' },
  { code: '58', flag: '🇻🇪', name: 'Venezuela' }
]
